## Genome Generation
Given a number of chromosome pairs and genes, randomly generates chromosomes with genes distributed at random indices throughout.

In [1]:
# import packages
import random
import string
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import numpy as np
import networkx as nx
from IPython.display import display
# import functions
from functions import *
from genome_generator import *
from meiosis_simu import *

In [2]:
genome=genomecreate(3, 20, 407)
print_genome(genome)

=== Chr1 | Length: 1220 bp ===
Gene  Position ChrA_Before ChrB_Before
   C       234           C           c
   P       347           P           p
   S       485           S           s
   D       624           D           d
   H       715           H           h
   E       998           E           e
   F      1189           F           f

=== Chr2 | Length: 1269 bp ===
Gene  Position ChrA_Before ChrB_Before
   A        99           A           a
   T       516           T           t
   Q       891           Q           q
   B       975           B           b
   G       991           G           g
   N      1228           N           n

=== Chr3 | Length: 1190 bp ===
Gene  Position ChrA_Before ChrB_Before
   I       272           I           i
   K       347           K           k
   O       355           O           o
   L       440           L           l
   M       510           M           m
   R       819           R           r
   J       918           J           j

In [3]:
genotypes=[]

for _ in range(2000):
    g1 = meiosis(genome)
    genotype = fertilization(g1,"a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t")
    genotypes.append(genotype)
    df_genotypes = pd.DataFrame(genotypes, columns=["Genotype"])

print(df_genotypes.head())

                                            Genotype
0  aa/bb/cc/dd/ee/ff/gg/hh/Ii/Jj/Kk/Ll/Mm/nn/Oo/p...
1  aa/bb/Cc/Dd/Ee/Ff/gg/Hh/Ii/jj/kk/ll/mm/Nn/oo/P...
2  Aa/bb/Cc/Dd/Ee/Ff/gg/Hh/Ii/jj/Kk/Ll/Mm/nn/Oo/P...
3  aa/Bb/cc/dd/ee/ff/Gg/hh/ii/Jj/kk/ll/mm/Nn/oo/p...
4  Aa/Bb/cc/dd/ee/ff/Gg/hh/Ii/jj/Kk/Ll/Mm/Nn/Oo/p...

In [4]:
genotypes2=[]

for _ in range(1000):
    g1 = meiosis(genome)
    g2=meiosis(genome)
    genotype = fertilization(g1,g2)
    genotypes2.append(genotype)
    df_genotypes2 = pd.DataFrame(genotypes2, columns=["Genotype"])

In [5]:
recomb_matrix = 100*compute_recombination_matrix(df_genotypes)
recomb_matrix = recomb_matrix.astype(float)
print(recomb_matrix.values.dtype) 
display(recomb_matrix.round(3))

float64

,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T
A,0.00,36.20,52.25,51.40,51.30,50.20,36.75,51.60,49.90,50.95,50.65,50.95,51.05,45.85,50.75,51.45,32.45,51.15,51.05,18.00
B,36.20,0.00,50.85,50.90,51.60,51.90,0.55,51.10,48.80,48.95,48.85,48.55,49.05,9.65,48.95,51.35,3.75,48.95,51.55,18.20
C,52.25,50.85,0.00,16.45,31.75,39.25,51.00,20.35,50.25,51.40,50.30,50.30,49.90,50.20,50.10,4.20,50.90,50.90,9.70,51.65
D,51.40,50.90,16.45,0.00,15.30,22.80,50.95,3.90,48.60,50.15,48.75,48.95,48.15,50.05,48.75,12.25,50.95,49.65,6.75,51.10
E,51.30,51.60,31.75,15.30,0.00,7.50,51.65,11.40,49.50,50.55,49.85,50.45,49.55,50.55,49.95,27.55,51.25,50.35,22.05,51.10
F,50.20,51.90,39.25,22.80,7.50,0.00,51.95,18.90,48.60,49.15,48.85,49.25,48.65,51.15,48.85,35.05,51.55,48.95,29.55,50.90
G,36.75,0.55,51.00,50.95,51.65,51.95,0.00,51.05,48.35,48.60,48.40,48.10,48.60,9.10,48.50,51.50,4.30,48.50,51.70,18.75
H,51.60,51.10,20.35,3.90,11.40,18.90,51.05,0.00,49.40,50.75,49.55,49.95,48.95,50.25,49.55,16.15,50.95,50.45,10.65,51.80
I,49.90,48.80,50.25,48.60,49.50,48.60,48.35,49.40,0.00,27.45,3.45,6.95,10.25,48.55,3.75,49.55,48.45,23.25,48.95,48.90
J,50.95,48.95,51.40,50.15,50.55,49.15,48.60,50.75,27.45,0.00,24.00,20.50,17.20,48.20,23.70,51.50,48.80,4.20,51.50,50.55
K,50.65,48.85,50.30,48.75,49.85,48.85,48.40,49.55,3.45,24.00,0.00,3.50,6.80,48.30,0.30,49.90,48.50,19.80,49.30,49.25
L,50.95,48.55,50.30,48.95,50.45,49.25,48.10,49.95,6.95,20.50,3.50,0.00,3.30,47.60,3.20,50.10,48.30,16.30,49.70,49.65
M,51.05,49.05,49.90,48.15,49.55,48.65,48.60,48.95,10.25,17.20,6.80,3.30,0.00,48.20,6.50,49.60,48.70,13.00,49.10,50.05
N,45.85,9.65,50.20,50.05,50.55,51.15,9.10,50.25,48.55,48.20,48.30,47.60,48.20,0.00,48.30,51.10,13.40,48.30,50.90,27.85
O,50.75,48.95,50.10,48.75,49.95,48.85,48.50,49.55,3.75,23.70,0.30,3.20,6.50,48.30,0.00,49.70,48.60,19.50,49.30,49.25
P,51.45,51.35,4.20,12.25,27.55,35.05,51.50,16.15,49.55,51.50,49.90,50.10,49.60,51.10,49.70,0.00,51.20,51.10,5.50,51.35
Q,32.45,3.75,50.90,50.95,51.25,51.55,4.30,50.95,48.45,48.80,48.50,48.30,48.70,13.40,48.60,51.20,0.00,48.60,51.30,14.45
R,51.15,48.95,50.90,49.65,50.35,48.95,48.50,50.45,23.25,4.20,19.80,16.30,13.00,48.30,19.50,51.10,48.60,0.00,50.90,50.45
S,51.05,51.55,9.70,6.75,22.05,29.55,51.70,10.65,48.95,51.50,49.30,49.70,49.10,50.90,49.30,5.50,51.30,50.90,0.00,51.35
T,18.00,18.20,51.65,51.10,51.10,50.90,18.75,51.80,48.90,50.55,49.25,49.65,50.05,27.85,49.25,51.35,14.45,50.45,51.35,0.00

###

##### This will display the distance matrix of genes, grouped by the chromosomes they are on:

In [6]:
groups = group_loci_by_linkage(recomb_matrix)
chrom_matrices = get_chromosome_matrices(recomb_matrix, groups)
display_chromosome_matrices(chrom_matrices)

Linking A-B with r=36.200
Linking A-G with r=36.750
Linking A-N with r=45.850
Linking A-Q with r=32.450
Linking A-T with r=18.000
Linking B-G with r=0.550
Linking B-N with r=9.650
Linking B-Q with r=3.750
Linking B-T with r=18.200
Linking C-D with r=16.450
Linking C-E with r=31.750
Linking C-F with r=39.250
Linking C-H with r=20.350
Linking C-P with r=4.200
Linking C-S with r=9.700
Linking D-E with r=15.300
Linking D-F with r=22.800
Linking D-H with r=3.900
Linking D-P with r=12.250
Linking D-S with r=6.750
Linking E-F with r=7.500
Linking E-H with r=11.400
Linking E-P with r=27.550
Linking E-S with r=22.050
Linking F-H with r=18.900
Linking F-P with r=35.050
Linking F-S with r=29.550
Linking G-N with r=9.100
Linking G-Q with r=4.300
Linking G-T with r=18.750
Linking H-P with r=16.150
Linking H-S with r=10.650
Linking I-J with r=27.450
Linking I-K with r=3.450
Linking I-L with r=6.950
Linking I-M with r=10.250
Linking I-O with r=3.750
Linking I-R with r=23.250
Linking J-K with r=24.000
Linking J-L with r=20.500
Linking J-M with r=17.200
Linking J-O with r=23.700
Linking J-R with r=4.200
Linking K-L with r=3.500
Linking K-M with r=6.800
Linking K-O with r=0.300
Linking K-R with r=19.800
Linking L-M with r=3.300
Linking L-O with r=3.200
Linking L-R with r=16.300
Linking M-O with r=6.500
Linking M-R with r=13.000
Linking N-Q with r=13.400
Linking N-T with r=27.850
Linking O-R with r=19.500
Linking P-S with r=5.500
Linking Q-T with r=14.450

In [7]:
map_genes(chrom_matrices["Chr1"])
map_genes(chrom_matrices["Chr2"])
map_genes(chrom_matrices["Chr3"])

Mapped positions:
A: 2.15 cM
B: 38.35 cM
G: 38.85 cM
N: 47.95 cM
Q: 34.55 cM
T: 20.15 cM

Total absolute error: 0.2
Mapped positions:
C: 41.66 cM
D: 25.26 cM
E: 9.96 cM
F: 2.46 cM
H: 21.36 cM
P: 37.46 cM
S: 31.96 cM

Total absolute error: 0.5
Mapped positions:
I: 13.77 cM
J: 41.17 cM
K: 17.17 cM
L: 20.67 cM
M: 23.97 cM
O: 17.47 cM
R: 36.97 cM

Total absolute error: 0.2

array([13.76807083, 41.16807083, 17.16807083, 20.66807083, 23.96807083,
       17.46807083, 36.96807083])